# Generated by Django 6.0.7 on 2026-07-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_checkout_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paystack_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
