# Generated by Django 6.0.7 on 2026-08-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='customer_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
