# Generated by Django 6.0.7 on 2026-08-21 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0010_importrates_sourcedunit_duty_rate_and_more'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('approval', 'Purchase approval'), ('sourcing', 'Import sourcing')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('closed', 'Closed')], default='open', max_length=10)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('import_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='imports.importrequest')),
                ('purchase_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='purchases.purchaserequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('import_request__isnull', True), ('kind', 'approval'), ('purchase_request__isnull', False)), models.Q(('import_request__isnull', False), ('kind', 'sourcing'), ('purchase_request__isnull', True)), _connector='OR'), name='ticket_subject_matches_kind'), models.CheckConstraint(condition=models.Q(models.Q(('claimed_by__isnull', True), ('status', 'open')), models.Q(('status', 'open'), _negated=True), _connector='OR'), name='open_ticket_is_unclaimed')],
            },
        ),
    ]
