# Generated by Django 6.0.7 on 2026-08-21 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0010_importrates_sourcedunit_duty_rate_and_more'),
        ('inquiries', '0003_inquiry_replied_at_inquiry_replied_by_inquiry_reply_and_more'),
        ('purchases', '0001_initial'),
        ('tickets', '0002_raise_tickets_for_existing_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='ticket_subject_matches_kind',
        ),
        migrations.AddField(
            model_name='ticket',
            name='inquiry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='inquiries.inquiry'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='kind',
            field=models.CharField(choices=[('approval', 'Purchase approval'), ('sourcing', 'Import sourcing'), ('enquiry', 'Enquiry')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('import_request__isnull', True), ('inquiry__isnull', True), ('kind', 'approval'), ('purchase_request__isnull', False)), models.Q(('import_request__isnull', False), ('inquiry__isnull', True), ('kind', 'sourcing'), ('purchase_request__isnull', True)), models.Q(('import_request__isnull', True), ('inquiry__isnull', False), ('kind', 'enquiry'), ('purchase_request__isnull', True)), _connector='OR'), name='ticket_subject_matches_kind'),
        ),
    ]
