# Generated by Django 6.0.7 on 2026-08-27 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
        ('imports', '0010_importrates_sourcedunit_duty_rate_and_more'),
        ('inquiries', '0004_alter_inquiry_car'),
        ('purchases', '0001_initial'),
        ('tickets', '0004_raise_tickets_for_existing_enquiries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='ticket_subject_matches_kind',
        ),
        migrations.AddField(
            model_name='ticket',
            name='dealer_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='dealers.dealerapplication'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='kind',
            field=models.CharField(choices=[('approval', 'Purchase approval'), ('sourcing', 'Import sourcing'), ('enquiry', 'Enquiry'), ('dealer', 'Dealer application')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dealer_application__isnull', True), ('import_request__isnull', True), ('inquiry__isnull', True), ('kind', 'approval'), ('purchase_request__isnull', False)), models.Q(('dealer_application__isnull', True), ('import_request__isnull', False), ('inquiry__isnull', True), ('kind', 'sourcing'), ('purchase_request__isnull', True)), models.Q(('dealer_application__isnull', True), ('import_request__isnull', True), ('inquiry__isnull', False), ('kind', 'enquiry'), ('purchase_request__isnull', True)), models.Q(('dealer_application__isnull', False), ('import_request__isnull', True), ('inquiry__isnull', True), ('kind', 'dealer'), ('purchase_request__isnull', True)), _connector='OR'), name='ticket_subject_matches_kind'),
        ),
    ]
