# Generated by Django 6.0.7 on 2026-07-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='state',
        ),
        migrations.AddField(
            model_name='car',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=5),
        ),
    ]
