# Generated by Django 6.0.7 on 2026-08-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('headline', models.CharField(max_length=120)),
                ('subline', models.CharField(blank=True, max_length=200)),
                ('cta_label', models.CharField(blank=True, max_length=40)),
                ('cta_url', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Only the most recently updated active banner is served.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
