# Generated by Django 6.0.7 on 2026-08-11 10:24

import cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_herobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='video',
            field=models.FileField(blank=True, help_text='Optional. Muted and looping, desktop only. Strip the audio track before uploading.', upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm']), cars.models.validate_hero_video_size]),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(help_text='Poster frame, always required - it is what renders on the first paint, on mobile, and whenever the video cannot play.', upload_to='hero/'),
        ),
    ]
