# Generated by Django 6.0.7 on 2026-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_herobanner_video_alter_herobanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('suv', 'SUV'), ('saloon', 'Saloon'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('pickup', 'Pickup'), ('van', 'Van'), ('convertible', 'Convertible')], max_length=12),
        ),
        migrations.AddField(
            model_name='car',
            name='drivetrain',
            field=models.CharField(blank=True, choices=[('2wd', '2WD'), ('awd', 'AWD'), ('4wd', '4WD')], max_length=3),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_cc',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='exterior_colour',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_colour',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='reference',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
