# Generated by Django 6.0.7 on 2026-08-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_body_type_car_drivetrain_car_engine_cc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_source',
            field=models.URLField(blank=True),
        ),
    ]
