# Generated by Django 6.0.7 on 2026-08-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, help_text='Chassis number for Japanese imports. Leave blank until confirmed - but once set it must be unique across listings.', max_length=17, verbose_name='VIN / chassis number'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(condition=models.Q(('vin', ''), _negated=True), fields=('vin',), name='unique_vin_when_set', violation_error_message='Another listing already uses this VIN / chassis number.'),
        ),
    ]
