# Generated by Django 6.0.7 on 2026-08-13 06:17

from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def start_the_clock(apps, schema_editor):
    """Give every existing listing a full window from today.

    Leaving them NULL would read as "never expires" and quietly exempt the
    whole current catalogue from the feature that was just added.
    """
    Car = apps.get_model('cars', 'Car')
    Car.objects.filter(expires_at__isnull=True).update(
        expires_at=timezone.now() + timedelta(days=settings.LISTING_LIFETIME_DAYS)
    )


def stop_the_clock(apps, schema_editor):
    # Reversing the field removes the column anyway; this keeps the migration
    # reversible without pretending it can restore what was never there.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_vin_car_unique_vin_when_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this listing drops off the site. Filled in on creation; clear it to keep a listing up indefinitely.', null=True),
        ),
        migrations.RunPython(start_the_clock, stop_the_clock),
    ]
