# Generated by Django 6.0.7 on 2026-08-13 06:19

import cars.video
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_car_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo link. Paste the share URL; the embed is worked out from it.', validators=[cars.video.validate_video_url], verbose_name='Walkthrough video'),
        ),
    ]
