# Generated by Django 6.0.7 on 2026-09-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_video_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroBanner',
        ),
    ]
