# Generated by Django 6.0.7 on 2026-07-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
