# Generated by Django 6.0.7 on 2026-07-27 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('car_description', models.CharField(max_length=200)),
                ('current_stage', models.CharField(choices=[('ordered', 'Ordered'), ('shipped', 'Shipped'), ('at_port', 'At Port'), ('clearing', 'Customs Clearing'), ('delivered', 'Delivered')], default='ordered', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('ordered', 'Ordered'), ('shipped', 'Shipped'), ('at_port', 'At Port'), ('clearing', 'Customs Clearing'), ('delivered', 'Delivered')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='imports.importorder')),
            ],
        ),
    ]
