# Generated by Django 6.0.7 on 2026-08-05 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carimage'),
        ('imports', '0003_importorder_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cars.car'),
        ),
    ]
