# Generated by Django 6.0.7 on 2026-08-14 14:39

import django.db.models.deletion
import imports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_shorten_car_descriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(help_text='Desired model year. Refused here if it is too old to clear.', validators=[imports.models.validate_import_age])),
                ('budget_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sourcing', 'Sourcing'), ('awaiting_selection', 'Awaiting selection'), ('agreed', 'Agreement pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(validators=[imports.models.validate_import_age])),
                ('chassis_number', models.CharField(blank=True, max_length=30)),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, help_text='Auction grade, e.g. 4.5 or R.', max_length=10)),
                ('exterior_colour', models.CharField(blank=True, max_length=40)),
                ('auction_sheet_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='sourced/')),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('freight_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dollar_rate', models.DecimalField(decimal_places=2, help_text='KES per USD, as quoted. Pinned so an old quote still reads.', max_digits=8)),
                ('duty_kes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('clearing_kes', models.DecimalField(decimal_places=2, default=0, help_text='Port, agent and transport charges.', max_digits=12)),
                ('service_fee_kes', models.DecimalField(decimal_places=2, default=0, help_text="Goldride's commission on this unit.", max_digits=12)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='offered', max_length=10)),
                ('rejected_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='imports.importrequest')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'selected')), fields=('request',), name='one_selected_unit_per_request', violation_error_message='This request already has a unit selected.')],
            },
        ),
    ]
