# Generated by Django 6.0.7 on 2026-08-17 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_video_url'),
        ('imports', '0007_importrequest_sourcedunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedunit',
            name='pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcedunit',
            name='pushed_to_car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_from', to='cars.car'),
        ),
    ]
