# Generated by Django 6.0.7 on 2026-08-17 06:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_sourcedunit_pushed_at_sourcedunit_pushed_to_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedunit',
            name='duty_kes',
        ),
        migrations.AddField(
            model_name='sourcedunit',
            name='customs_value_kes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="KRA's assessed value. Blank uses CIF.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sourcedunit',
            name='excise_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Percent. Banded by engine capacity.', max_digits=5),
        ),
    ]
