# Generated by Django 6.0.7 on 2026-08-17 07:31

import django.utils.timezone
from decimal import Decimal
from django.conf import settings as django_settings
from django.db import migrations, models


def pin_existing_rates(apps, schema_editor):
    """Existing units were computed against the settings values, so that is
    what they must keep. Leaving them null would break the arithmetic outright
    and silently re-rate them the moment the table gains a row."""
    SourcedUnit = apps.get_model('imports', 'SourcedUnit')
    SourcedUnit.objects.filter(duty_rate__isnull=True).update(
        duty_rate=django_settings.IMPORT_DUTY_RATE,
        vat_rate=django_settings.IMPORT_VAT_RATE,
        idf_rate=django_settings.IMPORT_IDF_RATE,
        rdl_rate=django_settings.IMPORT_RDL_RATE,
    )
    SourcedUnit.objects.filter(excise_rate__isnull=True).update(
        excise_rate=django_settings.IMPORT_EXCISE_RATE,
    )


def seed_rates(apps, schema_editor):
    """One starting row, so the admin has something to edit rather than an
    empty table and an invisible settings fallback."""
    ImportRates = apps.get_model('imports', 'ImportRates')
    if not ImportRates.objects.exists():
        ImportRates.objects.create(
            duty_rate=django_settings.IMPORT_DUTY_RATE,
            excise_rate=django_settings.IMPORT_EXCISE_RATE,
            vat_rate=django_settings.IMPORT_VAT_RATE,
            idf_rate=django_settings.IMPORT_IDF_RATE,
            rdl_rate=django_settings.IMPORT_RDL_RATE,
            stock_markup=django_settings.PUSH_TO_STOCK_MARKUP_PERCENT,
            note='Carried over from settings when rates became editable.',
        )


def unseed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0009_remove_sourcedunit_duty_kes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_rate', models.DecimalField(decimal_places=2, default=Decimal('25'), max_digits=5)),
                ('excise_rate', models.DecimalField(decimal_places=2, default=Decimal('25'), help_text='Starting point only - excise is banded by engine capacity, so it is set per unit.', max_digits=5)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('16'), max_digits=5)),
                ('idf_rate', models.DecimalField(decimal_places=2, default=Decimal('3.5'), max_digits=5)),
                ('rdl_rate', models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=5)),
                ('stock_markup', models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='Default margin when a rejected unit is pushed to stock.', max_digits=5)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, help_text='Where these came from - a Finance Act, a circular.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Import rates',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sourcedunit',
            name='duty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sourcedunit',
            name='idf_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sourcedunit',
            name='rdl_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sourcedunit',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sourcedunit',
            name='excise_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percent. Banded by engine capacity - set this one per unit.', max_digits=5, null=True),
        ),
            migrations.RunPython(pin_existing_rates, unseed),
        migrations.RunPython(seed_rates, unseed),
    ]
