# Generated by Django 6.0.7 on 2026-08-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
