# Generated by Django 6.0.7 on 2026-08-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
