# Generated by Django 6.0.7 on 2026-08-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_checkout_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
