# Generated by Django 6.0.7 on 2026-08-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_checkout_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
