# Generated by Django 6.0.7 on 2026-08-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_recorded_at_payment_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
