# Generated by Django 6.0.7 on 2026-08-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_paymentevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=8)),
                ('trigger', models.CharField(choices=[('automatic', 'Scheduled sweep'), ('command', 'Management command'), ('staff', 'Asked for by staff')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checked', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
