# Generated by Django 6.0.7 on 2026-08-27 15:09

import dealers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_video_url'),
        ('dealers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('logbook', 'Logbook'), ('id', 'ID or passport'), ('kra_pin', 'KRA PIN certificate'), ('import_entry', 'Import entry'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=dealers.models.document_path, validators=[dealers.models.validate_document])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dealerlisting',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='dealers.dealerapplication'),
        ),
        migrations.AlterField(
            model_name='dealerlisting',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='dealers.dealer'),
        ),
        migrations.AddConstraint(
            model_name='dealerlisting',
            constraint=models.CheckConstraint(condition=models.Q(('dealer__isnull', False), ('application__isnull', False), _connector='OR'), name='listing_belongs_to_someone'),
        ),
        migrations.AddField(
            model_name='dealerdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dealers.dealerapplication'),
        ),
    ]
