# Generated by Django 6.0.7 on 2026-08-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_dealerdocument_dealerlisting_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='website',
        ),
        migrations.RemoveField(
            model_name='dealerapplication',
            name='website',
        ),
        migrations.AddField(
            model_name='dealer',
            name='seller_type',
            field=models.CharField(choices=[('individual', 'Private seller'), ('dealer', 'Dealership')], default='individual', max_length=12),
        ),
        migrations.AddField(
            model_name='dealerapplication',
            name='id_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='dealerapplication',
            name='seller_type',
            field=models.CharField(choices=[('individual', 'Private seller'), ('dealer', 'Dealership')], default='individual', max_length=12),
        ),
        migrations.AlterField(
            model_name='dealerapplication',
            name='dealership_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='dealerapplication',
            name='fleet_size',
            field=models.PositiveIntegerField(blank=True, help_text='Roughly how many cars a dealership has to sell.', null=True),
        ),
    ]
