# Generated by Django 6.0.7 on 2026-08-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_backfill_seller_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerdocument',
            name='kind',
            field=models.CharField(choices=[('business_reg', 'Certificate of incorporation or business registration'), ('kra_pin', 'KRA PIN certificate'), ('vat', 'VAT certificate'), ('trade_licence', 'Trade licence (county permit)'), ('id', 'National ID or passport'), ('dealer_form', "Dealer's application form"), ('letter', 'Headed application letter'), ('insurance', 'Insurance certificate'), ('logbook', 'Logbook'), ('import_entry', 'Import entry'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
