# Generated by Django 6.0.7 on 2026-09-09 08:16

import dealers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_alter_dealerdocument_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerdocument',
            name='file',
            field=models.FileField(storage=dealers.models.private_document_storage, upload_to=dealers.models.document_path, validators=[dealers.models.validate_document]),
        ),
    ]
