"""
Django settings for goldride_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import  dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')

# Social sign-in. Blank means that provider is simply switched off.
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')
LINKEDIN_CLIENT_ID = config('LINKEDIN_CLIENT_ID', default='')
LINKEDIN_CLIENT_SECRET = config('LINKEDIN_CLIENT_SECRET', default='')
LINKEDIN_REDIRECT_URI = config('LINKEDIN_REDIRECT_URI', default='')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG')

allowed_hosts_str = config('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'goldride_app',
    'cars',
    'rest_framework',
    'inquiries',
    'django_filters',
    'imports',
    'rest_framework.authtoken',
    'payments',
    'purchases',
    'corsheaders',
    'drf_spectacular',
]

# Browsers block a React dev server from calling this API unless the origin
# is allowed here. Comma-separated in .env; these are the usual dev ports.
cors_origins_str = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000',
)
CORS_ALLOWED_ORIGINS = [o.strip() for o in cors_origins_str.split(',') if o.strip()]
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'goldride_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'goldride_project.wsgi.application'




# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Fallback to local SQLite if DATABASE_URL environment variable is missing
        default=f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}",
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_RATES": {
        "inquiries": "5/hour",
        "tracking": "20/hour",
        "payments": "10/hour",
        "purchases": "5/hour",
        "register": "10/hour",
        "social": "30/hour",
        "login": "10/hour",
        "verify": "20/hour",
    },
        "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 12,
        "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Goldride Motors API",
    "DESCRIPTION": "Car listings, customer enquiries, import tracking, and card / M-PESA payments.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Without these, several models share a field name and the generated
    # client ends up with types called Status5d2Enum.
    "ENUM_NAME_OVERRIDES": {
        "ImportStageEnum": "imports.models.ImportOrder.STAGE_CHOICES",
        "PaymentStatusEnum": "payments.models.Payment.STATUS_CHOICES",
        "PaymentMethodEnum": "payments.models.Payment.METHOD_CHOICES",
        "PurchaseStatusEnum": "purchases.models.PurchaseRequest.STATUS_CHOICES",
        "PurchaseMethodEnum": "purchases.models.PurchaseRequest.METHOD_CHOICES",
        "CarConditionEnum": "cars.models.Car.condition_choices",
        "CarAvailabilityEnum": "cars.models.Car.avilability_choices",
    },
}
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@goldridemotors.co.ke'

# Where the confirmation link points (this API), and where it sends the
# browser afterwards (the React app).
SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000')
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')

# Three days. Long enough for an email left until the weekend, short enough
# that a forwarded link stops working.
EMAIL_VERIFICATION_TIMEOUT = config(
    'EMAIL_VERIFICATION_TIMEOUT', default=60 * 60 * 24 * 3, cast=int
)

# Tests only. PBKDF2 is deliberately slow, and the suite creates hundreds of
# users - that cost was most of a three minute run. This hasher is weak on
# purpose and never touches a real password: the branch cannot be reached
# outside `manage.py test`.
if 'test' in sys.argv:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
