"""
Django settings for goldride_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from decimal import Decimal
from pathlib import Path
from decouple import config
import os
import  dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')

# Social sign-in. Blank means that provider is simply switched off.
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')
LINKEDIN_CLIENT_ID = config('LINKEDIN_CLIENT_ID', default='')
LINKEDIN_CLIENT_SECRET = config('LINKEDIN_CLIENT_SECRET', default='')
LINKEDIN_REDIRECT_URI = config('LINKEDIN_REDIRECT_URI', default='')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

allowed_hosts_str = config('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]

# Render injects the service's public hostname. Reading it means the app works
# on whatever URL Render hands out without that URL being hardcoded here.
RENDER_HOST = config('RENDER_EXTERNAL_HOSTNAME', default='')
if RENDER_HOST and RENDER_HOST not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_HOST)
elif config('RENDER', default=False, cast=bool):
    # Belt and braces. On 2026-08-19 the live service answered its own URL with
    # 400 DisallowedHost and ALLOWED_HOSTS holding nothing but localhost, so
    # RENDER_EXTERNAL_HOSTNAME plainly did not arrive - it is documented but not
    # guaranteed. RENDER itself is set on every instance, so when we know we are
    # on Render and nobody has named the host, trust the platform's own domain.
    # Render routes by hostname, so the only Host headers that reach this service
    # are its own; the leading dot matches subdomains and keeps the site up
    # rather than down while the real hostname is missing.
    ALLOWED_HOSTS.append('.onrender.com')

# Django 4+ rejects cross-origin POSTs - including the admin login - unless the
# origin is listed here, scheme included.
# A leading dot in ALLOWED_HOSTS is Django's subdomain wildcard; the equivalent
# here is an explicit "*", and dropping those entries instead - as this did -
# leaves the admin login unpostable whenever a wildcard is all we have.
CSRF_TRUSTED_ORIGINS = [
    f"https://*{host}" if host.startswith(".") else f"https://{host}"
    for host in ALLOWED_HOSTS
    if host not in ("localhost", "127.0.0.1", "*")
]

# Render terminates TLS at its proxy and forwards plain HTTP, so without this
# Django believes every request is insecure: request.is_secure() returns False,
# secure cookies are never set, and SSL redirects loop.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# --- HTTPS enforcement -----------------------------------------------------
# Follows DEBUG rather than needing its own switch: turning debug off for a
# deploy is the same decision as turning these on, and a second flag is one
# more thing to forget. Still overridable for the awkward case of running
# locally with DEBUG=False, where redirecting to https://localhost - which has
# no certificate - just breaks the site.
#
# Every one of these depends on SECURE_PROXY_SSL_HEADER above being correct.
# Without it Django never sees a secure request, SECURE_SSL_REDIRECT sends the
# browser to HTTPS, the proxy forwards plain HTTP again, and it loops forever.
SECURE_HTTPS = config('SECURE_HTTPS', default=not DEBUG, cast=bool)

SECURE_SSL_REDIRECT = SECURE_HTTPS
SESSION_COOKIE_SECURE = SECURE_HTTPS
CSRF_COOKIE_SECURE = SECURE_HTTPS

# HSTS is the one setting here that is hard to undo: browsers cache the
# instruction to refuse plain HTTP for this domain and honour it even if the
# header stops being sent. So it starts at an hour. Raise it deliberately -
# a day, then a week - and only go to a year once HTTPS has been reliable for
# a while. Setting a year on day one means a certificate problem locks
# everybody out for a year.
SECURE_HSTS_SECONDS = config(
    'SECURE_HSTS_SECONDS', default=3600 if SECURE_HTTPS else 0, cast=int
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HTTPS

# Deliberately off. Preloading ships the domain inside browsers themselves,
# and getting removed takes months. Not something to enable at a one hour
# max-age, and never worth it for a site that might yet need a plain-HTTP
# subdomain.
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'goldride_app',
    'cars',
    'rest_framework',
    'inquiries',
    'django_filters',
    'imports',
    'rest_framework.authtoken',
    'payments',
    'purchases',
    'corsheaders',
    'drf_spectacular',
]

# Browsers block a React dev server from calling this API unless the origin
# is allowed here. Comma-separated in .env; these are the usual dev ports.
cors_origins_str = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000',
)
CORS_ALLOWED_ORIGINS = [o.strip() for o in cors_origins_str.split(',') if o.strip()]
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'goldride_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'goldride_project.wsgi.application'




# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Fallback to local SQLite if DATABASE_URL environment variable is missing
        default=f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}",
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_RATES": {
        "inquiries": "5/hour",
        "imports": "5/hour",
        "tracking": "20/hour",
        "payments": "10/hour",
        "purchases": "5/hour",
        "register": "10/hour",
        "social": "30/hour",
        "login": "10/hour",
        "verify": "20/hour",
    },
        "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 12,
        "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Goldride Motors API",
    "DESCRIPTION": "Car listings, customer enquiries, import tracking, and card / M-PESA payments.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Without these, several models share a field name and the generated
    # client ends up with types called Status5d2Enum.
    "ENUM_NAME_OVERRIDES": {
        "ImportStageEnum": "imports.models.ImportOrder.STAGE_CHOICES",
        "PaymentStatusEnum": "payments.models.Payment.STATUS_CHOICES",
        "PaymentMethodEnum": "payments.models.Payment.METHOD_CHOICES",
        "PurchaseStatusEnum": "purchases.models.PurchaseRequest.STATUS_CHOICES",
        "PurchaseMethodEnum": "purchases.models.PurchaseRequest.METHOD_CHOICES",
        "CarConditionEnum": "cars.models.Car.condition_choices",
        "CarAvailabilityEnum": "cars.models.Car.avilability_choices",
        # Added with the sourcing models - both have a "status" and collided
        # with each other, resolving to names like Status71bEnum.
        "ImportRequestStatusEnum": "imports.models.ImportRequest.STATUS_CHOICES",
        "SourcedUnitStatusEnum": "imports.models.SourcedUnit.STATUS_CHOICES",
    },
}
# Console stays the default so a fresh checkout and the test suite need no
# mail server. Production sets EMAIL_BACKEND to the SMTP backend; until it
# does, every email this system sends is printed to a log and reaches nobody.
EMAIL_BACKEND = config(
    'EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
# STARTTLS on 587 suits nearly every provider. A few only offer implicit TLS
# on 465, which is a different mechanism - set EMAIL_USE_SSL and EMAIL_PORT
# together for those. They are mutually exclusive; Django raises if both are
# on, so TLS defers when SSL is asked for explicitly.
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=not EMAIL_USE_SSL, cast=bool)

# Without this a mail server that accepts the connection and then hangs holds
# the worker thread open indefinitely - and these emails are sent inline,
# during a request that is approving a sale.
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)

DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL', default='noreply@goldridemotors.co.ke'
)
# Where "tell sales" messages go. Was hardcoded at five call sites.
SALES_EMAIL = config('SALES_EMAIL', default='sales@goldridemotors.co.ke')

# Where the confirmation link points (this API), and where it sends the
# browser afterwards (the React app).
SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000')
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')

# Three days. Long enough for an email left until the weekend, short enough
# that a forwarded link stops working.
EMAIL_VERIFICATION_TIMEOUT = config(
    'EMAIL_VERIFICATION_TIMEOUT', default=60 * 60 * 24 * 3, cast=int
)

# How long a listing stays on the site before it needs renewing. A car sold
# privately months ago should not still be answering searches; making the
# seller confirm it is still for sale is the cheapest way to find out.
LISTING_LIFETIME_DAYS = config('LISTING_LIFETIME_DAYS', default=45, cast=int)

# KEBS will not clear a used import that is 8 or more years old, counted from
# the year of first registration - so the oldest permissible age is 7. The
# client's documentation calls this "the 7-year rule" and KEBS phrases it as
# "under 8 years"; they are the same constraint counted from opposite ends.
# Refusing a unit at the quote stage is far cheaper than at the port.
IMPORT_MAX_VEHICLE_AGE_YEARS = config(
    'IMPORT_MAX_VEHICLE_AGE_YEARS', default=7, cast=int
)

# KRA's charges on an imported vehicle, as percentages. Settings rather than
# constants because every one of them has moved at some point and a rate
# change must not need a deploy. Excise varies by engine capacity, so its rate
# lives on the unit; this is only the default.
IMPORT_DUTY_RATE = config('IMPORT_DUTY_RATE', default=Decimal('25'), cast=Decimal)
IMPORT_EXCISE_RATE = config('IMPORT_EXCISE_RATE', default=Decimal('25'), cast=Decimal)
IMPORT_VAT_RATE = config('IMPORT_VAT_RATE', default=Decimal('16'), cast=Decimal)
IMPORT_IDF_RATE = config('IMPORT_IDF_RATE', default=Decimal('3.5'), cast=Decimal)
IMPORT_RDL_RATE = config('IMPORT_RDL_RATE', default=Decimal('2'), cast=Decimal)

# Default margin when a rejected sourced unit is converted into stock. Applied
# to landed cost, not to the quoted total - the quote already carried a
# commission for the customer who walked away, and charging it twice would
# price the car out of its own market.
PUSH_TO_STOCK_MARKUP_PERCENT = config(
    'PUSH_TO_STOCK_MARKUP_PERCENT', default=15, cast=Decimal
)

# Mail failures are logged rather than raised, so they need somewhere to land.
# Console handler because Render captures stdout - a file would be written to
# an ephemeral disk and lost on the next deploy.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'plain': {'format': '{levelname} {asctime} {name} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'plain'},
    },
    'loggers': {
        'goldride': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}

# Tests only. PBKDF2 is deliberately slow, and the suite creates hundreds of
# users - that cost was most of a three minute run. This hasher is weak on
# purpose and never touches a real password: the branch cannot be reached
# outside `manage.py test`.
if 'test' in sys.argv:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']
    # Every send logs a line, and the suite sends dozens - it buries the
    # actual test output. Warnings and errors still surface.
    LOGGING['loggers']['goldride']['level'] = 'WARNING'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
