"""
Django settings for goldride_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from decimal import Decimal
from pathlib import Path
from decouple import config
import os
import  dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')

# Social sign-in. Blank means that provider is simply switched off.
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')
LINKEDIN_CLIENT_ID = config('LINKEDIN_CLIENT_ID', default='')
LINKEDIN_CLIENT_SECRET = config('LINKEDIN_CLIENT_SECRET', default='')
LINKEDIN_REDIRECT_URI = config('LINKEDIN_REDIRECT_URI', default='')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

allowed_hosts_str = config('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]

# Some hosts inject the service's public hostname rather than letting you name
# it. `PUBLIC_HOSTNAME` is that hook, kept platform-neutral: set it to whatever
# the host exports and the app answers on a URL nobody had to hardcode.
PUBLIC_HOSTNAME = config('PUBLIC_HOSTNAME', default='')
if PUBLIC_HOSTNAME and PUBLIC_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(PUBLIC_HOSTNAME)

# Django 4+ rejects cross-origin POSTs - including the admin login - unless the
# origin is listed here, scheme included.
# A leading dot in ALLOWED_HOSTS is Django's subdomain wildcard; the equivalent
# here is an explicit "*", and dropping those entries instead - as this did -
# leaves the admin login unpostable whenever a wildcard is all we have.
CSRF_TRUSTED_ORIGINS = [
    f"https://*{host}" if host.startswith(".") else f"https://{host}"
    for host in ALLOWED_HOSTS
    if host not in ("localhost", "127.0.0.1", "*")
]

# Nearly every managed host terminates TLS at a proxy and forwards plain HTTP.
# Without this Django believes every request is insecure: request.is_secure()
# returns False, secure cookies are never set, and SSL redirects loop.
#
# It trusts the X-Forwarded-Proto header, so the app must sit behind a proxy
# that sets it. Exposed directly to the internet, a client could send the
# header itself and be believed.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# --- HTTPS enforcement -----------------------------------------------------
# Follows DEBUG rather than needing its own switch: turning debug off for a
# deploy is the same decision as turning these on, and a second flag is one
# more thing to forget. Still overridable for the awkward case of running
# locally with DEBUG=False, where redirecting to https://localhost - which has
# no certificate - just breaks the site.
#
# Every one of these depends on SECURE_PROXY_SSL_HEADER above being correct.
# Without it Django never sees a secure request, SECURE_SSL_REDIRECT sends the
# browser to HTTPS, the proxy forwards plain HTTP again, and it loops forever.
SECURE_HTTPS = config('SECURE_HTTPS', default=not DEBUG, cast=bool)

SECURE_SSL_REDIRECT = SECURE_HTTPS
SESSION_COOKIE_SECURE = SECURE_HTTPS
CSRF_COOKIE_SECURE = SECURE_HTTPS

# HSTS is the one setting here that is hard to undo: browsers cache the
# instruction to refuse plain HTTP for this domain and honour it even if the
# header stops being sent. So it starts at an hour. Raise it deliberately -
# a day, then a week - and only go to a year once HTTPS has been reliable for
# a while. Setting a year on day one means a certificate problem locks
# everybody out for a year.
SECURE_HSTS_SECONDS = config(
    'SECURE_HSTS_SECONDS', default=3600 if SECURE_HTTPS else 0, cast=int
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HTTPS

# Deliberately off. Preloading ships the domain inside browsers themselves,
# and getting removed takes months. Not something to enable at a one hour
# max-age, and never worth it for a site that might yet need a plain-HTTP
# subdomain.
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)


# Application definition

INSTALLED_APPS = [
    # First, deliberately: daphne takes over runserver so development speaks
    # the same protocol as production. A websocket that only works when
    # deployed is one nobody tests.
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'goldride_app',
    'cars',
    'rest_framework',
    'inquiries',
    'django_filters',
    'imports',
    'rest_framework.authtoken',
    'payments',
    'purchases',
    'tickets',
    'dealers',
    'chat',
    'corsheaders',
    'drf_spectacular',
    # Only supplies the storage backend; harmless when no credentials are set,
    # because STORAGES then points at the filesystem instead.
    'cloudinary_storage',
    'cloudinary',
]

# Browsers block a React dev server from calling this API unless the origin
# is allowed here. Comma-separated in .env; these are the usual dev ports.
cors_origins_str = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000',
)
# Trailing slashes are stripped rather than rejected. An origin is scheme,
# host and port and nothing else, so django-cors-headers refuses one with a
# path - and `/` is a path. Every browser and dashboard shows a URL with that
# slash, so pasting one in is the obvious thing to do, and it failed the whole
# deploy at `manage.py check` with the site otherwise ready to serve.
CORS_ALLOWED_ORIGINS = [
    origin.strip().rstrip('/')
    for origin in cors_origins_str.split(',')
    if origin.strip().rstrip('/')
]
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Directly after SecurityMiddleware, as WhiteNoise requires. Without it
    # nothing serves the admin's own CSS once DEBUG is off: Django stops
    # serving static files itself, and there is no nginx in front of this.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'goldride_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'goldride_project.wsgi.application'


# --- realtime ---------------------------------------------------------------
ASGI_APPLICATION = "goldride_project.asgi.application"

# Redis when there is a Redis, memory when there is not.
#
# The in-memory layer is per process: two workers cannot see each other's
# groups, so a message published by one is invisible to a customer connected
# to the other. That is fine for development and for a single-instance
# deploy, and silently wrong the moment the service scales - hence reading
# the URL from the environment rather than choosing here.
REDIS_URL = config('REDIS_URL', default='')

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
    }




# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Fallback to local SQLite if DATABASE_URL environment variable is missing
        default=f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}",
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        # Refuses a password that is mostly the username or email address.
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # 12, not Django's 8. Length is the only property that actually costs
        # an attacker anything, and 8 characters is minutes on rented hardware.
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},
    },
    {
        # Django ships a list of the 20,000 commonest passwords.
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        # Three of: lower, upper, digit, symbol. Three rather than four on
        # purpose - see the note in validators.py.
        'NAME': 'goldride_app.validators.ComplexityValidator',
        'OPTIONS': {'required': 3},
    },
    {
        # Stops "aaaaaaaaaaaa" and "abcabcabcabc", which clear every rule above.
        'NAME': 'goldride_app.validators.RepetitionValidator',
        'OPTIONS': {'max_run': 4},
    },
]

# How long a password reset link stays good. Django's own default is 3 days,
# which is a long time for a link that hands over an account; a reset is
# something people do immediately or not at all.
PASSWORD_RESET_TIMEOUT = config(
    'PASSWORD_RESET_TIMEOUT', default=60 * 60 * 2, cast=int
)

# --- who may sign up -------------------------------------------------------
# An address that is merely well-formed is not an address. `tung6767@test.com`
# passes every syntax check and reaches nobody, and an account there can never
# verify, never reset a password and never be told its car arrived.
#
# Three rules, applied at signup and whenever an address is changed. See
# goldride_app/validators.py for what each one does.
EMAIL_REJECT_RESERVED_DOMAINS = config(
    'EMAIL_REJECT_RESERVED_DOMAINS', default=True, cast=bool
)
EMAIL_REJECT_DISPOSABLE_DOMAINS = config(
    'EMAIL_REJECT_DISPOSABLE_DOMAINS', default=True, cast=bool
)
# The DNS check. Costs one lookup on signup and fails open when the resolver
# is unreachable, so a DNS wobble cannot stop the world registering.
EMAIL_REQUIRE_DELIVERABLE_DOMAIN = config(
    'EMAIL_REQUIRE_DELIVERABLE_DOMAIN', default=True, cast=bool
)
EMAIL_DNS_TIMEOUT = config('EMAIL_DNS_TIMEOUT', default=5, cast=int)
# Anything else to refuse, comma separated, without a deploy.
EMAIL_BLOCKED_DOMAINS = config('EMAIL_BLOCKED_DOMAINS', default='')
REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_RATES": {
        "inquiries": "5/hour",
        "imports": "5/hour",
        "tracking": "20/hour",
        "payments": "10/hour",
        "purchases": "5/hour",
        "register": "10/hour",
        "social": "30/hour",
        # Both sign-in doors share this scope - `/api/auth/login/` and
        # `/api/auth/login/email/` - so it cannot be sidestepped by moving to
        # the other one. Counted per IP address for anonymous callers.
        #
        # Five is deliberately tight for password guessing, and it is also
        # five typos before a real customer is locked out for the hour. Raise
        # it with LOGIN_THROTTLE_RATE if that turns out to bite; the shape is
        # "<number>/hour". Watch it in particular for customers behind one
        # office or mobile-carrier address, who share the count.
        "login": config('LOGIN_THROTTLE_RATE', default='5/hour'),
        "verify": "20/hour",
        # Covers requesting a link, spending one, and changing a known
        # password. Low: this is the endpoint somebody walks an address list
        # through, and a legitimate person resets a password once.
        "password_reset": "5/hour",
        # A dealership applies once. Anything beyond a handful an hour
        # from one address is not a dealership.
        "dealers": "5/hour",
        # Chat is a conversation, not a form submission - a rate that suits an
        # enquiry would cut somebody off mid-sentence. High enough to type
        # freely, low enough that a runaway client cannot flood the inbox.
        "chat": "120/hour",
    },
        "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 12,
        "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    # Deny by default. DRF ships with AllowAny, which means a view that simply
    # forgets to declare a permission is open to the internet rather than
    # broken - the failure is silent, and looks exactly like a working view.
    # That already happened here once: see the docstring on InitiatePaymentView,
    # which took a payment reference from anybody at all.
    #
    # Every genuinely public endpoint now says so out loud with AllowAny - the
    # catalogue, the token-addressed tracking pages, the two provider webhooks
    # and the auth entry points. The cost of this line is that a new public
    # view needs one explicit declaration; the benefit is that forgetting one
    # returns 401 instead of leaking.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Goldride Motors API",
    "DESCRIPTION": "Car listings, customer enquiries, import tracking, and card / M-PESA payments.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # The schema names all 134 routes, every staff endpoint among them, with
    # their parameters and response shapes. That is a free map of the estate
    # for anybody deciding where to push, and drf-spectacular serves it to
    # AllowAny unless told otherwise. Staff only in production; open in debug
    # so local development keeps its Swagger page without a login.
    "SERVE_PERMISSIONS": (
        ["rest_framework.permissions.AllowAny"]
        if DEBUG
        else ["rest_framework.permissions.IsAdminUser"]
    ),
    # Without these, several models share a field name and the generated
    # client ends up with types called Status5d2Enum.
    "ENUM_NAME_OVERRIDES": {
        "ImportStageEnum": "imports.models.ImportOrder.STAGE_CHOICES",
        "PaymentStatusEnum": "payments.models.Payment.STATUS_CHOICES",
        "PaymentMethodEnum": "payments.models.Payment.METHOD_CHOICES",
        "PurchaseStatusEnum": "purchases.models.PurchaseRequest.STATUS_CHOICES",
        "PurchaseMethodEnum": "purchases.models.PurchaseRequest.METHOD_CHOICES",
        "CarConditionEnum": "cars.models.Car.condition_choices",
        "CarAvailabilityEnum": "cars.models.Car.avilability_choices",
        # Added with the sourcing models - both have a "status" and collided
        # with each other, resolving to names like Status71bEnum.
        "ImportRequestStatusEnum": "imports.models.ImportRequest.STATUS_CHOICES",
        "SourcedUnitStatusEnum": "imports.models.SourcedUnit.STATUS_CHOICES",
    },
}
# Console stays the default so a fresh checkout and the test suite need no
# mail server. Production sets EMAIL_BACKEND to the SMTP backend; until it
# does, every email this system sends is printed to a log and reaches nobody.
EMAIL_BACKEND = config(
    'EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
# STARTTLS on 587 suits nearly every provider. A few only offer implicit TLS
# on 465, which is a different mechanism - set EMAIL_USE_SSL and EMAIL_PORT
# together for those. They are mutually exclusive; Django raises if both are
# on, so TLS defers when SSL is asked for explicitly.
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=not EMAIL_USE_SSL, cast=bool)

# Without this a mail server that accepts the connection and then hangs holds
# the worker thread open indefinitely - and these emails are sent inline,
# during a request that is approving a sale.
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)

# Used only by goldride_app.email_backends.ResendBackend, which goes out over
# HTTPS instead of SMTP - managed hosts block outbound SMTP far more often than
# they block a normal API call. The EMAIL_HOST settings above still apply if
# EMAIL_BACKEND is pointed back at Django's SMTP backend.
RESEND_API_KEY = config('RESEND_API_KEY', default='')

DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL', default='noreply@goldridemotors.co.ke'
)
# Where "tell sales" messages go. Was hardcoded at five call sites.
SALES_EMAIL = config('SALES_EMAIL', default='sales@goldridemotors.co.ke')

# How long a new dealer has to set their password before the invitation
# link dies. A week: long enough to survive a holiday, short enough that a
# forwarded email does not stay usable forever.
DEALER_ACTIVATION_TIMEOUT = config(
    'DEALER_ACTIVATION_TIMEOUT', default=60 * 60 * 24 * 7, cast=int
)

# Where the confirmation link points (this API), and where it sends the
# browser afterwards (the React app).
# Both are joined to paths with an f-string, so a pasted trailing slash would
# produce `https://host//pay/<ref>/`. Some servers 404 that; all of them look
# wrong in an email a customer is reading.
SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000').rstrip('/')
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173').rstrip('/')

# How long a card checkout link is offered for.
#
# Ours, not Paystack's: their initialize call takes no expiry, so the URL they
# mint stays valid at their end whatever we do. What expires is our willingness
# to hand it out - after this the app stops showing it and offers a fresh one
# instead. That matters because a link is only worth showing while the price,
# the car and the reservation behind it still hold.
CHECKOUT_LINK_MINUTES = config('CHECKOUT_LINK_MINUTES', default=10, cast=int)

# How often the application reconciles pending payments against Paystack and
# Safaricom, on a background thread it starts itself. A dropped webhook means
# money taken and not recorded against an order, and until this existed the
# only thing that found it was a member of staff clicking a button.
#
# Set to 0 if an external scheduler runs `manage.py reconcile_payments`
# instead, so the two do not both sweep.
RECONCILE_INTERVAL_MINUTES = config(
    'RECONCILE_INTERVAL_MINUTES', default=30, cast=int
)

# How settled a payment must be before the sweep asks about it. Somebody is
# still typing a card number into a tab for the first minute or two of a
# payment's life; a live card checkout is separately protected by
# ABANDONED_GRACE in payments/reconciliation.py.
RECONCILE_STALE_MINUTES = config('RECONCILE_STALE_MINUTES', default=2, cast=int)

# Three days. Long enough for an email left until the weekend, short enough
# that a forwarded link stops working.
EMAIL_VERIFICATION_TIMEOUT = config(
    'EMAIL_VERIFICATION_TIMEOUT', default=60 * 60 * 24 * 3, cast=int
)

# How long a listing stays on the site before it needs renewing. A car sold
# privately months ago should not still be answering searches; making the
# seller confirm it is still for sale is the cheapest way to find out.
LISTING_LIFETIME_DAYS = config('LISTING_LIFETIME_DAYS', default=45, cast=int)

# KEBS will not clear a used import that is 8 or more years old, counted from
# the year of first registration - so the oldest permissible age is 7. The
# client's documentation calls this "the 7-year rule" and KEBS phrases it as
# "under 8 years"; they are the same constraint counted from opposite ends.
# Refusing a unit at the quote stage is far cheaper than at the port.
IMPORT_MAX_VEHICLE_AGE_YEARS = config(
    'IMPORT_MAX_VEHICLE_AGE_YEARS', default=7, cast=int
)

# KRA's charges on an imported vehicle, as percentages. Settings rather than
# constants because every one of them has moved at some point and a rate
# change must not need a deploy. Excise varies by engine capacity, so its rate
# lives on the unit; this is only the default.
IMPORT_DUTY_RATE = config('IMPORT_DUTY_RATE', default=Decimal('25'), cast=Decimal)
IMPORT_EXCISE_RATE = config('IMPORT_EXCISE_RATE', default=Decimal('25'), cast=Decimal)
IMPORT_VAT_RATE = config('IMPORT_VAT_RATE', default=Decimal('16'), cast=Decimal)
IMPORT_IDF_RATE = config('IMPORT_IDF_RATE', default=Decimal('3.5'), cast=Decimal)
IMPORT_RDL_RATE = config('IMPORT_RDL_RATE', default=Decimal('2'), cast=Decimal)

# Default margin when a rejected sourced unit is converted into stock. Applied
# to landed cost, not to the quoted total - the quote already carried a
# commission for the customer who walked away, and charging it twice would
# price the car out of its own market.
PUSH_TO_STOCK_MARKUP_PERCENT = config(
    'PUSH_TO_STOCK_MARKUP_PERCENT', default=15, cast=Decimal
)

# Mail failures are logged rather than raised, so they need somewhere to land.
# Console handler because a managed host captures stdout - a file would be written to
# an ephemeral disk and lost on the next deploy.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'plain': {'format': '{levelname} {asctime} {name} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'plain'},
    },
    'loggers': {
        'goldride': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}

# Tests only. PBKDF2 is deliberately slow, and the suite creates hundreds of
# users - that cost was most of a three minute run. This hasher is weak on
# purpose and never touches a real password: the branch cannot be reached
# outside `manage.py test`.
if 'test' in sys.argv:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']

    # example.com is the address domain RFC 2606 reserves for exactly this,
    # and ~155 fixtures across the suite use it. Blocking it in the test run
    # would mean rewriting all of them to prove a rule that production applies
    # anyway - so the reserved list is off here and the tests that cover it
    # switch it back on with override_settings.
    EMAIL_REJECT_RESERVED_DOMAINS = False
    # No test may depend on a DNS server answering.
    EMAIL_REQUIRE_DELIVERABLE_DOMAIN = False
    # Every send logs a line, and the suite sends dozens - it buries the
    # actual test output. Warnings and errors still surface.
    LOGGING['loggers']['goldride']['level'] = 'WARNING'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Where collectstatic gathers everything for WhiteNoise to serve.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --- uploaded files -------------------------------------------------------
# Cloudinary when it is configured, the local filesystem when it is not.
#
# Not a preference: a managed host with no persistent disk has nowhere to put
# an upload. Django refuses to serve /media/ once DEBUG is off, WhiteNoise
# serves only what collectstatic gathered, and the filesystem is wiped on every
# deploy - so a photograph uploaded through the admin returned 404 immediately
# and was gone for good shortly after. Both the hero and a car's photographs
# were lost that way before this existed.
#
# Reading the cloud name rather than a flag means development keeps writing to
# backend/media/ with nothing to switch, and a deploy that forgets the
# credentials falls back to the old broken behaviour rather than erroring at
# import - visible, but not a site that will not boot.
CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='')

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}

MEDIA_STORAGE_BACKEND = (
    'cloudinary_storage.storage.MediaCloudinaryStorage'
    if CLOUDINARY_CLOUD_NAME
    else 'django.core.files.storage.FileSystemStorage'
)

STORAGES = {
    "default": {
        "BACKEND": MEDIA_STORAGE_BACKEND,
    },
    "staticfiles": {
        # Hashed filenames plus a manifest, so a deploy cannot serve last
        # release's stylesheet out of somebody's cache. The manifest is also
        # why collectstatic has to run in the build: a missing file then fails
        # at deploy time rather than in front of a customer.
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
