# Generated by Django 6.0.7 on 2026-08-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_video_url'),
        ('inquiries', '0003_inquiry_replied_at_inquiry_replied_by_inquiry_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='cars.car'),
        ),
    ]
